// <auto-generated />
using System;
using DndCompanion.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DndCompanion.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260728120557_AddCharacterCombatStats")]
    partial class AddCharacterCombatStats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("DndCompanion.Domain.Entities.ActionDef", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RulesText")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.ToTable("ActionDefs");
                });

            modelBuilder.Entity("DndCompanion.Domain.Entities.ActionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DiceResultJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InitiativeSlot")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RoundNo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionLogId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionLogId", "CreatedUtc");

                    b.ToTable("ActionEntries");
                });

            modelBuilder.Entity("DndCompanion.Domain.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("DndCompanion.Domain.Entities.CampaignCharacter", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.HasKey("CampaignId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("CampaignCharacter");
                });

            modelBuilder.Entity("DndCompanion.Domain.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Abilities")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Alignment")
                        .HasColumnType("TEXT");

                    b.Property<int>("ArmorClass")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(10);

                    b.Property<string>("Background")
                        .HasColumnType("TEXT");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExpertSkills")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("None");

                    b.Property<int>("InitiativeBonus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProficiencyBonus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProficientSaves")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("None");

                    b.Property<string>("ProficientSkills")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("None");

                    b.Property<string>("Size")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Medium");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Speed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(30);

                    b.Property<string>("SpellSlots")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{\"Level1Current\":0,\"Level1Max\":0,\"Level2Current\":0,\"Level2Max\":0,\"Level3Current\":0,\"Level3Max\":0,\"Level4Current\":0,\"Level4Max\":0,\"Level5Current\":0,\"Level5Max\":0,\"Level6Current\":0,\"Level6Max\":0,\"Level7Current\":0,\"Level7Max\":0,\"Level8Current\":0,\"Level8Max\":0,\"Level9Current\":0,\"Level9Max\":0}");

                    b.Property<string>("Subclass")
                        .HasColumnType("TEXT");

                    b.Property<int>("TempHp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("DndCompanion.Domain.Entities.CharacterAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActionDefId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActionDefId");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterAction");
                });

            modelBuilder.Entity("DndCompanion.Domain.Entities.CharacterItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Attuned")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Equipped")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ItemId");

                    b.ToTable("CharacterItem");
                });

            modelBuilder.Entity("DndCompanion.Domain.Entities.CharacterSpell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AlwaysPrepared")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrepared")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SpellId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("SpellId");

                    b.ToTable("CharacterSpell");
                });

            modelBuilder.Entity("DndCompanion.Domain.Entities.ContentSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Attribution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContentSources");
                });

            modelBuilder.Entity("DndCompanion.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertiesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RulesText")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("WeightLb")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("Category", "Name");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("DndCompanion.Domain.Entities.Recording", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionLogId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionLogId");

                    b.ToTable("Recordings");
                });

            modelBuilder.Entity("DndCompanion.Domain.Entities.SessionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("SessionLogs");
                });

            modelBuilder.Entity("DndCompanion.Domain.Entities.Spell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CastingTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Components")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Concentration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RulesText")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScalingJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("Level", "Name");

                    b.ToTable("Spells");
                });

            modelBuilder.Entity("DndCompanion.Domain.Entities.StructuredNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecordingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.Property<double>("TStart")
                        .HasColumnType("REAL");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecordingId");

                    b.ToTable("StructuredNotes");
                });

            modelBuilder.Entity("DndCompanion.Domain.Entities.TranscriptSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<Guid>("RecordingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpeakerLabel")
                        .HasColumnType("TEXT");

                    b.Property<double>("TEnd")
                        .HasColumnType("REAL");

                    b.Property<double>("TStart")
                        .HasColumnType("REAL");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecordingId");

                    b.ToTable("TranscriptSegments");
                });

            modelBuilder.Entity("DndCompanion.Domain.Entities.ActionDef", b =>
                {
                    b.HasOne("DndCompanion.Domain.Entities.ContentSource", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("DndCompanion.Domain.Entities.ActionEntry", b =>
                {
                    b.HasOne("DndCompanion.Domain.Entities.SessionLog", "SessionLog")
                        .WithMany("Entries")
                        .HasForeignKey("SessionLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionLog");
                });

            modelBuilder.Entity("DndCompanion.Domain.Entities.CampaignCharacter", b =>
                {
                    b.HasOne("DndCompanion.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Characters")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DndCompanion.Domain.Entities.Character", "Character")
                        .WithMany("Campaigns")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("DndCompanion.Domain.Entities.CharacterAction", b =>
                {
                    b.HasOne("DndCompanion.Domain.Entities.ActionDef", "ActionDef")
                        .WithMany()
                        .HasForeignKey("ActionDefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DndCompanion.Domain.Entities.Character", "Character")
                        .WithMany("Actions")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionDef");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("DndCompanion.Domain.Entities.CharacterItem", b =>
                {
                    b.HasOne("DndCompanion.Domain.Entities.Character", "Character")
                        .WithMany("Items")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DndCompanion.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("DndCompanion.Domain.Entities.CharacterSpell", b =>
                {
                    b.HasOne("DndCompanion.Domain.Entities.Character", "Character")
                        .WithMany("Spells")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DndCompanion.Domain.Entities.Spell", "Spell")
                        .WithMany()
                        .HasForeignKey("SpellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Spell");
                });

            modelBuilder.Entity("DndCompanion.Domain.Entities.Item", b =>
                {
                    b.HasOne("DndCompanion.Domain.Entities.ContentSource", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("DndCompanion.Domain.Entities.Recording", b =>
                {
                    b.HasOne("DndCompanion.Domain.Entities.SessionLog", "SessionLog")
                        .WithMany("Recordings")
                        .HasForeignKey("SessionLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionLog");
                });

            modelBuilder.Entity("DndCompanion.Domain.Entities.SessionLog", b =>
                {
                    b.HasOne("DndCompanion.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Sessions")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("DndCompanion.Domain.Entities.Spell", b =>
                {
                    b.HasOne("DndCompanion.Domain.Entities.ContentSource", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("DndCompanion.Domain.Entities.StructuredNote", b =>
                {
                    b.HasOne("DndCompanion.Domain.Entities.Recording", "Recording")
                        .WithMany("Notes")
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recording");
                });

            modelBuilder.Entity("DndCompanion.Domain.Entities.TranscriptSegment", b =>
                {
                    b.HasOne("DndCompanion.Domain.Entities.Recording", "Recording")
                        .WithMany("Segments")
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recording");
                });

            modelBuilder.Entity("DndCompanion.Domain.Entities.Campaign", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("DndCompanion.Domain.Entities.Character", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Campaigns");

                    b.Navigation("Items");

                    b.Navigation("Spells");
                });

            modelBuilder.Entity("DndCompanion.Domain.Entities.Recording", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("Segments");
                });

            modelBuilder.Entity("DndCompanion.Domain.Entities.SessionLog", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Recordings");
                });
#pragma warning restore 612, 618
        }
    }
}
